cd "C:\test"
test.exe /SM "System manufacturer"
test.exe /SP "System Product Name"
test.exe /SV "System Version"
test.exe /SS "System Serial Number"
test.exe /SU "AUTO"
test.exe /SK "SKU"
test.exe /SF "To be filled by O.E.M."
test.exe /BS "MB-1234567890"
test.exe /BT "Default string"
test.exe /BLC "Default string"
test.exe /CM "Default string"
test.exe /CV "Default string"
test.exe /CS "Default string"
test.exe /CA "Default string"
test.exe /CSK "Default string"
pause